# Generated by Django 3.2 on 2023-08-15 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('licenses', '0002_auto_20220520_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='license_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'production'), (1, 'evaluation')]),
        ),
        migrations.AlterField(
            model_name='license',
            name='package',
            field=models.PositiveSmallIntegerField(choices=[(0, 'javascript_sdk'), (1, 'ios_sdk'), (2, 'android_sdk')]),
        ),
        migrations.CreateModel(
            name='NotificationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sending_date', models.DateTimeField(auto_now=True)),
                ('quantity_of_notificated_licenses', models.PositiveSmallIntegerField()),
                ('admin_poc', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to='licenses.client')),
            ],
        ),
    ]
